USE [KAIZEN]
GO

IF NOT EXISTS (  SELECT * FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'USERTYPE' AND COLUMN_NAME = 'USERCODE')
BEGIN
  ALTER TABLE USERTYPE
    ADD USERCODE VARCHAR(50) NULL
END;

GO
IF NOT EXISTS (  SELECT * FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'USERLOG' AND COLUMN_NAME = 'CREATEDDATE')
BEGIN
  ALTER TABLE USERLOG
    ADD CREATEDDATE DATETIME NULL
END
GO
