USE [KAIZEN]
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME = 'USERTYPE' AND COLUMN_NAME = 'USERCODE')
BEGIN
  UPDATE USERTYPE
  SET USERCODE = 'ADM'
  WHERE UserTypeId = 1 AND UserDesc = 'ADMIN';

  UPDATE USERTYPE
  SET USERCODE = 'EMP'
  WHERE UserTypeId = 2 AND UserDesc = 'EMPLOYEE';

  UPDATE USERTYPE
  SET USERCODE = 'FIN'
  WHERE UserTypeId = 3 AND UserDesc = 'FINANACE';

  UPDATE USERTYPE
  SET USERCODE = 'IED'
  WHERE UserTypeId = 4 AND UserDesc = 'IE DEPT';

  UPDATE USERTYPE
  SET USERCODE = 'MGR'
  WHERE UserTypeId = 5 AND UserDesc = 'MANAGER';
END;
GO